FROM node:14 AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

# Create app directory, this is in our container/in our image
WORKDIR /usr/src/api

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./


RUN npm global add @nestjs/cli
RUN npm install --production=true

RUN apt-get -q update && apt-get -qy install netcat

# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

RUN npm run build

EXPOSE 8080


CMD ["sh", "-c", "npx typeorm migration:run && npx start:prod"]